// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search/search.proto

package search

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddIndexRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	IndexJson            string   `protobuf:"bytes,3,opt,name=index_json,json=indexJson,proto3" json:"index_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIndexRequest) Reset()         { *m = AddIndexRequest{} }
func (m *AddIndexRequest) String() string { return proto.CompactTextString(m) }
func (*AddIndexRequest) ProtoMessage()    {}
func (*AddIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{0}
}

func (m *AddIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIndexRequest.Unmarshal(m, b)
}
func (m *AddIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIndexRequest.Marshal(b, m, deterministic)
}
func (m *AddIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIndexRequest.Merge(m, src)
}
func (m *AddIndexRequest) XXX_Size() int {
	return xxx_messageInfo_AddIndexRequest.Size(m)
}
func (m *AddIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIndexRequest proto.InternalMessageInfo

func (m *AddIndexRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddIndexRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *AddIndexRequest) GetIndexJson() string {
	if m != nil {
		return m.IndexJson
	}
	return ""
}

type AddIndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIndexResponse) Reset()         { *m = AddIndexResponse{} }
func (m *AddIndexResponse) String() string { return proto.CompactTextString(m) }
func (*AddIndexResponse) ProtoMessage()    {}
func (*AddIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{1}
}

func (m *AddIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIndexResponse.Unmarshal(m, b)
}
func (m *AddIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIndexResponse.Marshal(b, m, deterministic)
}
func (m *AddIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIndexResponse.Merge(m, src)
}
func (m *AddIndexResponse) XXX_Size() int {
	return xxx_messageInfo_AddIndexResponse.Size(m)
}
func (m *AddIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIndexResponse proto.InternalMessageInfo

type DeleteIndexRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexRequest) Reset()         { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()    {}
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{2}
}

func (m *DeleteIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexRequest.Unmarshal(m, b)
}
func (m *DeleteIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexRequest.Merge(m, src)
}
func (m *DeleteIndexRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexRequest.Size(m)
}
func (m *DeleteIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexRequest proto.InternalMessageInfo

func (m *DeleteIndexRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteIndexRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

type DeleteIndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexResponse) Reset()         { *m = DeleteIndexResponse{} }
func (m *DeleteIndexResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexResponse) ProtoMessage()    {}
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{3}
}

func (m *DeleteIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexResponse.Unmarshal(m, b)
}
func (m *DeleteIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexResponse.Marshal(b, m, deterministic)
}
func (m *DeleteIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexResponse.Merge(m, src)
}
func (m *DeleteIndexResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexResponse.Size(m)
}
func (m *DeleteIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexResponse proto.InternalMessageInfo

type SearchRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	QueryJson            string   `protobuf:"bytes,3,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{4}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SearchRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *SearchRequest) GetQueryJson() string {
	if m != nil {
		return m.QueryJson
	}
	return ""
}

type SearchResponse struct {
	Total                int64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MaxScore             float64         `protobuf:"fixed64,2,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Hits                 []*SearchResult `protobuf:"bytes,3,rep,name=hits,proto3" json:"hits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{5}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResponse) GetMaxScore() float64 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *SearchResponse) GetHits() []*SearchResult {
	if m != nil {
		return m.Hits
	}
	return nil
}

type SearchResult struct {
	Index                string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Score                float64  `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	SourceJson           string   `protobuf:"bytes,5,opt,name=source_json,json=sourceJson,proto3" json:"source_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{6}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SearchResult) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResult) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SearchResult) GetSourceJson() string {
	if m != nil {
		return m.SourceJson
	}
	return ""
}

type BulkRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Commands             []string `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkRequest) Reset()         { *m = BulkRequest{} }
func (m *BulkRequest) String() string { return proto.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()    {}
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{7}
}

func (m *BulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkRequest.Unmarshal(m, b)
}
func (m *BulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkRequest.Marshal(b, m, deterministic)
}
func (m *BulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkRequest.Merge(m, src)
}
func (m *BulkRequest) XXX_Size() int {
	return xxx_messageInfo_BulkRequest.Size(m)
}
func (m *BulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkRequest proto.InternalMessageInfo

func (m *BulkRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BulkRequest) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

type BulkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkResponse) Reset()         { *m = BulkResponse{} }
func (m *BulkResponse) String() string { return proto.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()    {}
func (*BulkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{8}
}

func (m *BulkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkResponse.Unmarshal(m, b)
}
func (m *BulkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkResponse.Marshal(b, m, deterministic)
}
func (m *BulkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkResponse.Merge(m, src)
}
func (m *BulkResponse) XXX_Size() int {
	return xxx_messageInfo_BulkResponse.Size(m)
}
func (m *BulkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkResponse proto.InternalMessageInfo

type IndexDocumentRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	DocId                int64    `protobuf:"varint,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	DocJson              string   `protobuf:"bytes,4,opt,name=doc_json,json=docJson,proto3" json:"doc_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexDocumentRequest) Reset()         { *m = IndexDocumentRequest{} }
func (m *IndexDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*IndexDocumentRequest) ProtoMessage()    {}
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{9}
}

func (m *IndexDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexDocumentRequest.Unmarshal(m, b)
}
func (m *IndexDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexDocumentRequest.Marshal(b, m, deterministic)
}
func (m *IndexDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexDocumentRequest.Merge(m, src)
}
func (m *IndexDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_IndexDocumentRequest.Size(m)
}
func (m *IndexDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexDocumentRequest proto.InternalMessageInfo

func (m *IndexDocumentRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *IndexDocumentRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *IndexDocumentRequest) GetDocId() int64 {
	if m != nil {
		return m.DocId
	}
	return 0
}

func (m *IndexDocumentRequest) GetDocJson() string {
	if m != nil {
		return m.DocJson
	}
	return ""
}

type IndexDocumentResponse struct {
	DocId                int64    `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexDocumentResponse) Reset()         { *m = IndexDocumentResponse{} }
func (m *IndexDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*IndexDocumentResponse) ProtoMessage()    {}
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{10}
}

func (m *IndexDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexDocumentResponse.Unmarshal(m, b)
}
func (m *IndexDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexDocumentResponse.Marshal(b, m, deterministic)
}
func (m *IndexDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexDocumentResponse.Merge(m, src)
}
func (m *IndexDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_IndexDocumentResponse.Size(m)
}
func (m *IndexDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexDocumentResponse proto.InternalMessageInfo

func (m *IndexDocumentResponse) GetDocId() int64 {
	if m != nil {
		return m.DocId
	}
	return 0
}

type DeleteDocumentRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	DocId                int64    `protobuf:"varint,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentRequest) Reset()         { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()    {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{11}
}

func (m *DeleteDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentRequest.Unmarshal(m, b)
}
func (m *DeleteDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentRequest.Merge(m, src)
}
func (m *DeleteDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentRequest.Size(m)
}
func (m *DeleteDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentRequest proto.InternalMessageInfo

func (m *DeleteDocumentRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteDocumentRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *DeleteDocumentRequest) GetDocId() int64 {
	if m != nil {
		return m.DocId
	}
	return 0
}

type DeleteDocumentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentResponse) Reset()         { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()    {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{12}
}

func (m *DeleteDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentResponse.Unmarshal(m, b)
}
func (m *DeleteDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentResponse.Merge(m, src)
}
func (m *DeleteDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentResponse.Size(m)
}
func (m *DeleteDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddIndexRequest)(nil), "search.AddIndexRequest")
	proto.RegisterType((*AddIndexResponse)(nil), "search.AddIndexResponse")
	proto.RegisterType((*DeleteIndexRequest)(nil), "search.DeleteIndexRequest")
	proto.RegisterType((*DeleteIndexResponse)(nil), "search.DeleteIndexResponse")
	proto.RegisterType((*SearchRequest)(nil), "search.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "search.SearchResponse")
	proto.RegisterType((*SearchResult)(nil), "search.SearchResult")
	proto.RegisterType((*BulkRequest)(nil), "search.BulkRequest")
	proto.RegisterType((*BulkResponse)(nil), "search.BulkResponse")
	proto.RegisterType((*IndexDocumentRequest)(nil), "search.IndexDocumentRequest")
	proto.RegisterType((*IndexDocumentResponse)(nil), "search.IndexDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "search.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "search.DeleteDocumentResponse")
}

func init() { proto.RegisterFile("search/search.proto", fileDescriptor_3c662bebbc5127a4) }

var fileDescriptor_3c662bebbc5127a4 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0x62, 0xc7, 0x24, 0x93, 0x36, 0xa0, 0x49, 0x5c, 0x8c, 0x4b, 0x20, 0xf2, 0x29, 0xa7,
	0x20, 0xca, 0x81, 0x13, 0x12, 0xa0, 0x0a, 0x29, 0x15, 0x02, 0xc9, 0xf9, 0x80, 0xc8, 0x78, 0x17,
	0xd5, 0x10, 0x7b, 0x5d, 0xaf, 0x8d, 0xd2, 0x0b, 0x7c, 0x0b, 0x7f, 0x8a, 0x3c, 0xeb, 0x4d, 0x6c,
	0xa7, 0x15, 0x87, 0xa8, 0xa7, 0x64, 0xe6, 0xed, 0xbe, 0x37, 0x6f, 0x67, 0xc6, 0x30, 0x96, 0x3c,
	0xc8, 0xc2, 0xeb, 0x57, 0xea, 0x67, 0x91, 0x66, 0x22, 0x17, 0x68, 0xa9, 0xc8, 0xfb, 0x0e, 0x8f,
	0x3f, 0x30, 0xb6, 0x4c, 0x18, 0xdf, 0xfa, 0xfc, 0xa6, 0xe0, 0x32, 0x47, 0x1b, 0xac, 0x20, 0x4d,
	0xd7, 0x11, 0x73, 0x3a, 0xb3, 0xce, 0x7c, 0xe0, 0xf7, 0x82, 0x34, 0x5d, 0x32, 0x9c, 0x02, 0x44,
	0xe5, 0xb1, 0x75, 0x12, 0xc4, 0xdc, 0xe9, 0x12, 0x34, 0xa0, 0xcc, 0x97, 0x20, 0xe6, 0x7b, 0xf8,
	0x87, 0x14, 0x89, 0x63, 0xd4, 0xe0, 0x2b, 0x29, 0x12, 0x0f, 0xe1, 0xc9, 0x5e, 0x47, 0xa6, 0x22,
	0x91, 0xdc, 0xbb, 0x02, 0xbc, 0xe4, 0x1b, 0x9e, 0xf3, 0xe3, 0xe5, 0x3d, 0x1b, 0xc6, 0x0d, 0xae,
	0x4a, 0x82, 0xc1, 0xe9, 0x8a, 0x8c, 0x1e, 0x6d, 0xee, 0xa6, 0xe0, 0xd9, 0x6d, 0xc3, 0x1c, 0x65,
	0xc8, 0x5c, 0x0c, 0x23, 0xad, 0xa2, 0x74, 0x71, 0x02, 0xbd, 0x5c, 0xe4, 0xc1, 0x86, 0x54, 0x0c,
	0x5f, 0x05, 0x78, 0x0e, 0x83, 0x38, 0xd8, 0xae, 0x65, 0x28, 0x32, 0x25, 0xd2, 0xf1, 0xfb, 0x71,
	0xb0, 0x5d, 0x95, 0x31, 0xce, 0xc1, 0xbc, 0x8e, 0x72, 0xe9, 0x18, 0x33, 0x63, 0x3e, 0xbc, 0x98,
	0x2c, 0xaa, 0x76, 0xed, 0x88, 0x8b, 0x4d, 0xee, 0xd3, 0x09, 0xef, 0x0f, 0x9c, 0xd4, 0xb3, 0xa5,
	0x18, 0x95, 0xaa, 0x2d, 0x51, 0x80, 0x08, 0x66, 0x7e, 0x9b, 0x6a, 0x33, 0xf4, 0x1f, 0x47, 0xd0,
	0x8d, 0x18, 0xd5, 0x6f, 0xf8, 0xdd, 0x88, 0x95, 0x37, 0x55, 0x31, 0x26, 0x15, 0xa3, 0x02, 0x7c,
	0x09, 0x43, 0x29, 0x8a, 0x2c, 0xe4, 0xca, 0x6e, 0x8f, 0x08, 0x40, 0xa5, 0xc8, 0xef, 0x7b, 0x18,
	0x7e, 0x2c, 0x36, 0x3f, 0xff, 0xf3, 0xa6, 0x2e, 0xf4, 0x43, 0x11, 0xc7, 0x41, 0xc2, 0xa4, 0xd3,
	0x9d, 0x19, 0xf3, 0x81, 0xbf, 0x8b, 0xbd, 0x11, 0x9c, 0x28, 0x86, 0xaa, 0x4f, 0xbf, 0x61, 0x42,
	0x8d, 0xbb, 0x14, 0x61, 0x11, 0xf3, 0x24, 0x3f, 0xae, 0x5d, 0x36, 0x58, 0x4c, 0x84, 0xeb, 0x9d,
	0xd5, 0x1e, 0x13, 0xe1, 0x92, 0xe1, 0x33, 0xe8, 0x97, 0x69, 0x32, 0x65, 0xd2, 0x9d, 0x47, 0x4c,
	0x84, 0xe4, 0x68, 0x01, 0x76, 0x4b, 0xbf, 0x6a, 0xe4, 0x9e, 0xaa, 0x53, 0xa3, 0xf2, 0x18, 0xd8,
	0x6a, 0xdc, 0x1e, 0xb2, 0x60, 0xcf, 0x81, 0xb3, 0xb6, 0x8a, 0x2a, 0xeb, 0xe2, 0xaf, 0xa1, 0x07,
	0x7b, 0xc5, 0xb3, 0x5f, 0x51, 0xc8, 0xf1, 0x1d, 0xf4, 0xf5, 0x82, 0xe1, 0x53, 0x3d, 0x3c, 0xad,
	0xd5, 0x76, 0x9d, 0x43, 0xa0, 0xf2, 0xf9, 0x09, 0x86, 0xb5, 0xfd, 0x41, 0x57, 0x1f, 0x3c, 0x5c,
	0x50, 0xf7, 0xfc, 0x4e, 0xac, 0xe2, 0xf9, 0x0c, 0xa7, 0x8d, 0x87, 0xc4, 0xe7, 0xfa, 0xf4, 0x5d,
	0xfd, 0x75, 0xa7, 0xf7, 0xa0, 0x15, 0xdb, 0x57, 0x18, 0x35, 0x1f, 0x00, 0xa7, 0x4d, 0xf1, 0x36,
	0xdf, 0x8b, 0xfb, 0xe0, 0x8a, 0xf0, 0x2d, 0x58, 0xea, 0xd9, 0xd0, 0x6e, 0x2f, 0x98, 0x22, 0x38,
	0x3b, 0xd8, 0x3b, 0x75, 0xf1, 0x35, 0x98, 0xe5, 0xc0, 0xe2, 0x58, 0xe3, 0xb5, 0x05, 0x70, 0x27,
	0xcd, 0xa4, 0xba, 0xf2, 0xcd, 0xa2, 0x2f, 0xed, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x79, 0xf0, 0x36, 0x80, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	AddIndex(ctx context.Context, in *AddIndexRequest, opts ...grpc.CallOption) (*AddIndexResponse, error)
	// rpc GetIndex(GetIndexRequest) returns (GetIndexResponse);
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// The Bulk API does not fail due to failures in one of the actions. If a single action fails for whatever reason, it will continue to process the remainder of the actions after it. When the bulk API returns, it will provide a status for each action (in the same order it was sent in) so that you can check if a specific action failed or not.
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) AddIndex(ctx context.Context, in *AddIndexRequest, opts ...grpc.CallOption) (*AddIndexResponse, error) {
	out := new(AddIndexResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/AddIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/DeleteIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error) {
	out := new(IndexDocumentResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/IndexDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/DeleteDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	out := new(BulkResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/Bulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	AddIndex(context.Context, *AddIndexRequest) (*AddIndexResponse, error)
	// rpc GetIndex(GetIndexRequest) returns (GetIndexResponse);
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	IndexDocument(context.Context, *IndexDocumentRequest) (*IndexDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// The Bulk API does not fail due to failures in one of the actions. If a single action fails for whatever reason, it will continue to process the remainder of the actions after it. When the bulk API returns, it will provide a status for each action (in the same order it was sent in) so that you can check if a specific action failed or not.
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) AddIndex(ctx context.Context, req *AddIndexRequest) (*AddIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIndex not implemented")
}
func (*UnimplementedSearchServiceServer) DeleteIndex(ctx context.Context, req *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (*UnimplementedSearchServiceServer) IndexDocument(ctx context.Context, req *IndexDocumentRequest) (*IndexDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexDocument not implemented")
}
func (*UnimplementedSearchServiceServer) DeleteDocument(ctx context.Context, req *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (*UnimplementedSearchServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedSearchServiceServer) Bulk(ctx context.Context, req *BulkRequest) (*BulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bulk not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_AddIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).AddIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/AddIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).AddIndex(ctx, req.(*AddIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/DeleteIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/IndexDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexDocument(ctx, req.(*IndexDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/Bulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIndex",
			Handler:    _SearchService_AddIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _SearchService_DeleteIndex_Handler,
		},
		{
			MethodName: "IndexDocument",
			Handler:    _SearchService_IndexDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _SearchService_DeleteDocument_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _SearchService_Bulk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/search.proto",
}
